# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reduce, Reuse, Refactor
email: javierieh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tech blog about .net, ruby, javascript and other technologies
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://javierieh.github.io/" # the base hostname & protocol for your site
twitter_username: javierieh
github_username:  javierieh
paginate: 5
# Build settings
markdown: kramdown
theme: pixyll
gems: [jekyll-paginate]
date_format: "%Y %B %e"
text:
  post:
    minute_read: minutes